# Generated by Django 3.1 on 2020-08-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='product',
            new_name='voted_product',
        ),
    ]
